name: ShellCheck

on:
  push:
    paths:
      - 'scripts/*.sh'
      - '.github/workflows/shellcheck.yml'
  pull_request:
    paths:
      - 'scripts/*.sh'
      - '.github/workflows/shellcheck.yml'

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: './scripts'
